version: '{build}'
image: Visual Studio 2019 Preview
configuration: Release
init:
- ps: |
    Write-Host Initializing...
    git config --global core.autocrlf true
install:
- cmd: git submodule update -q --init
before_build:
- ps: nuget restore Sakuno.CefSharp.Wpf\Sakuno.CefSharp.Wpf.sln
build_script:
- ps: |
    msbuild Sakuno.CefSharp.Wpf\src\Sakuno.CefSharp.Wpf\Sakuno.CefSharp.Wpf.csproj /p:Platform=x86,Configuration=$env:CONFIGURATION /v:m
    msbuild Sakuno.CefSharp.Wpf\src\Sakuno.CefSharp.Wpf\Sakuno.CefSharp.Wpf.csproj /p:Platform=x64,Configuration=$env:CONFIGURATION /v:m
on_finish:
- ps: |
    Get-ChildItem -Recurse -Filter Sakuno.CefSharp.Wpf.dll | Select-Object FullName, Length
    Write-Host Finished.
