version: '{build}'
image: Visual Studio 2017
init:
- ps: |
    Write-Host Initializing
    git config --global core.autocrlf true
    git clone https://github.com/KodamaSakuno/Sakuno.UserInterface 2>&1 | Out-Null
before_build:
- cmd: nuget restore
build:
  project: Sakuno.UserInterfac\Sakuno.UserInterface.sln
  verbosity: minimal
on_finish:
- ps: Write-Host Finished.
