version: '{build}'
image: Visual Studio 2019 Preview
configuration: Release
init:
- ps: |
    $PSVersionTable
    $env:APPVEYOR_BUILD_FOLDER
    git config --global core.autocrlf true
on_finish:
- ps: Write-Host Finished.