version: '{build}'
image: Visual Studio 2019 Preview
configuration: Release
init:
- ps: |
    $PSVersionTable
    Write-Host
    $env:APPVEYOR_BUILD_FOLDER
    git config --global core.autocrlf true
install:
- ps: |
    (Get-Item -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0").GetValue("InstallationFolder")
    (Get-Item -Path "Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v10.0").GetValue("ProductVersion")
build_script:
- ps: |
    Write-Host 'Build Script'
on_finish:
- ps: Write-Host Finished.