version: '{build}'
image: Visual Studio 2017
configuration: Release
init:
- ps: |
    Write-Host Initializing...
    git config --global core.autocrlf true
install:
- cmd: git submodule update -q --init
before_build:
- ps: nuget restore Sakuno.UserInterface\Sakuno.UserInterface.sln
build:
  project: Sakuno.UserInterface\Sakuno.UserInterface.sln
  MSBuildTargetsVerbose: true
  verbosity: detailed
on_finish:
- ps: Write-Host Finished.
