version: '{build}'
image: Visual Studio 2017
configuration: Release
init:
- ps: |
    Write-Host $env:APPVEYOR_BUILD_FOLDER
    git config --global core.autocrlf true
on_finish:
- ps: Write-Host Finished.
