version: '{build}'
image: Visual Studio 2017
init:
- ps: |
    Write-Host Initializing
    git config --global core.autocrlf true
install:
- cmd: git submodule update -q --init
before_build:
- ps: |
    Set-Location Sakuno.UserInterface
    nuget restore
build:
  project: Sakuno.UserInterface\Sakuno.UserInterface.sln
  verbosity: minimal
on_finish:
- ps: Write-Host Finished.
