version: '{build}'
image: Visual Studio 2017
configuration: Release
init:
- ps: |
    Write-Host Initializing...
    git config --global core.autocrlf true
install:
- cmd: git submodule update -q --init
before_build:
- ps: nuget restore Sakuno.CefSharp.Wpf\Sakuno.CefSharp.Wpf.sln
build:
  project: Sakuno.CefSharp.Wpf\Sakuno.CefSharp.Wpf.sln
  verbosity: minimal
on_finish:
- ps: |
    Get-ChildItem -Recurse -Filter Sakuno.CefSharp.Wpf.dll | Select-Object FullName, Length
    Write-Host Finished.
